name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.4.1
    - run: |
        npm install
        npm install react
        npm install react-scripts
    - run: npm run build
      env:
        CI: false
